package webdriver

var endpoints = [...]struct {
	Method         string
	Path           string
	Description    string
	Implementation interface{}
}{
	{"POST", "/session", "New Session", (*Client).Session},
	{"DELETE", "/session/{session id}", "Delete Session", (*session).Close},
	{"GET", "/status", "Status", (*Client).Status},
	{"GET", "/session/{session id}/timeouts", "Get Timeouts", nil},
	{"POST", "/session/{session id}/timeouts", "Set Timeouts", nil},
	{"POST", "/session/{session id}/url", "Navigate To", (*session).NavigateTo},
	{"GET", "/session/{session id}/url", "Get Current URL", (*session).GetCurrentURL},
	{"POST", "/session/{session id}/back", "Back", (*session).Back},
	{"POST", "/session/{session id}/forward", "Forward", (*session).Forward},
	{"POST", "/session/{session id}/refresh", "Refresh", (*session).Refresh},
	{"GET", "/session/{session id}/title", "Get Title", (*session).GetTitle},
	{"GET", "/session/{session id}/window", "Get Window Handle", (*session).GetWindowHandle},
	{"DELETE", "/session/{session id}/window", "Close Window", (*session).CloseWindow},
	{"POST", "/session/{session id}/window", "Switch To Window", (*session).SwitchToWindow},
	{"GET", "/session/{session id}/window/handles", "Get Window Handles", (*session).GetWindowHandles},
	{"POST", "/session/{session id}/window/new", "New Window", (*session).NewWindow},
	{"POST", "/session/{session id}/frame", "Switch To Frame", (*session).SwitchToFrame},
	{"POST", "/session/{session id}/frame/parent", "Switch To Parent Frame", nil},
	{"GET", "/session/{session id}/window/rect", "Get Window Rect", (*session).GetWindowRect},
	{"POST", "/session/{session id}/window/rect", "Set Window Rect", (*session).SetWindowRect},
	{"POST", "/session/{session id}/window/maximize", "Maximize Window", (*session).MaximizeWindow},
	{"POST", "/session/{session id}/window/minimize", "Minimize Window", (*session).MinimizeWindow},
	{"POST", "/session/{session id}/window/fullscreen", "Fullscreen Window", nil},
	{"GET", "/session/{session id}/element/active", "Get Active Element", nil},
	{"POST", "/session/{session id}/element", "Find Element", (*session).FindElement},
	{"POST", "/session/{session id}/elements", "Find Elements", (*session).FindElements},
	{"POST", "/session/{session id}/element/{element id}/element", "Find Element From Element", nil},
	{"POST", "/session/{session id}/element/{element id}/elements", "Find Elements From Element", nil},
	{"GET", "/session/{session id}/element/{element id}/selected", "Is Element Selected", nil},
	{"GET", "/session/{session id}/element/{element id}/attribute/{name}", "Get Element Attribute", (*element).GetElementAttribute},
	{"GET", "/session/{session id}/element/{element id}/property/{name}", "Get Element Property", (*element).GetElementProperty},
	{"GET", "/session/{session id}/element/{element id}/css/{property name}", "Get Element CSS Value", nil},
	{"GET", "/session/{session id}/element/{element id}/text", "Get Element Text", (*element).GetElementText},
	{"GET", "/session/{session id}/element/{element id}/name", "Get Element Tag Name", nil},
	{"GET", "/session/{session id}/element/{element id}/rect", "Get Element Rect", (*element).GetElementRect},
	{"GET", "/session/{session id}/element/{element id}/enabled", "Is Element Enabled", nil},
	{"POST", "/session/{session id}/element/{element id}/click", "Element Click", (*element).Click},
	{"POST", "/session/{session id}/element/{element id}/clear", "Element Clear", nil},
	{"POST", "/session/{session id}/element/{element id}/value", "Element Send Keys", (*element).SendKeys},
	{"GET", "/session/{session id}/source", "Get Page Source", nil},
	{"POST", "/session/{session id}/execute/sync", "Execute Script", nil},
	{"POST", "/session/{session id}/execute/async", "Execute Async Script", nil},
	{"GET", "/session/{session id}/cookie", "Get All Cookies", nil},
	{"GET", "/session/{session id}/cookie/{name}", "Get Named Cookie", nil},
	{"POST", "/session/{session id}/cookie", "Add Cookie", nil},
	{"DELETE", "/session/{session id}/cookie/{name}", "Delete Cookie", nil},
	{"DELETE", "/session/{session id}/cookie", "Delete All Cookies", nil},
	{"POST", "/session/{session id}/actions", "Perform Actions", (*session).Actions},
	{"DELETE", "/session/{session id}/actions", "Release Actions", nil},
	{"POST", "/session/{session id}/alert/dismiss", "Dismiss Alert", nil},
	{"POST", "/session/{session id}/alert/accept", "Accept Alert", (*session).AcceptAlert},
	{"GET", "/session/{session id}/alert/text", "Get Alert Text", nil},
	{"POST", "/session/{session id}/alert/text", "Send Alert Text", nil},
	{"GET", "/session/{session id}/screenshot", "Take Screenshot", nil},
	{"GET", "/session/{session id}/element/{element id}/screenshot", "Take Element Screenshot", nil},

	{"POST", "/session/{session id}/moveto", "Move To", (*element).MoveTo},
}
